# Generated by Django 3.1.4 on 2020-12-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('title', models.CharField(max_length=20, verbose_name='adi')),
                ('fuel', models.CharField(choices=[('B', 'Benzin'), ('D', 'Dizel'), ('Q', 'Qaz')], max_length=10, verbose_name='yanacaq novu:')),
                ('is_new', models.BooleanField(blank=True, null=True, verbose_name='tezedir')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images', verbose_name='sekil')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='sekil url')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
