# Generated by Django 3.1.4 on 2020-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201225_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='tezedir'),
        ),
    ]
